# Generated by Django 4.2.4 on 2023-09-07 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group_type',
        ),
        migrations.DeleteModel(
            name='GroupType',
        ),
    ]
