# Generated by Django 4.2.4 on 2023-09-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_group_group_type_delete_grouptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(default='jesus', max_length=70),
            preserve_default=False,
        ),
    ]
